discovery_io_exception=can't connect to discovery service